name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # or METRICS_TOKEN if you want private repos
          user: tediyo
          template: classic
          base: repositories
          plugin_repositories: yes
          filename: github-metrics.svg
          output_action: commit
          config_display_title: "📊 My Repository Stats"
