name: GitHub Repo Metrics

on:
  schedule: 
    - cron: "0 * * * *" # Every hour
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: tediyo
          template: classic
          base: repositories
          plugin_repositories: yes
          config_timezone: Africa/Addis_Ababa
          config_display: large
          config_display_title: "📊 My Repository Stats"
